name: slide_item
description: Flutter侧滑菜单组件
version: 1.0.0
author: 1453918362@qq.com
homepage: https://github.com/tsx1453/slide_item

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

